GET http://localhost:8080/userlist
Content-Type: application/json

###

GET http://localhost:8080/user/675402bb-51ae-4914-a9cb-d9f1b7237dfa
Content-Type: application/json

###

POST http://localhost:8080/createuser
Content-Type: application/json

{
    "Name": "Eduardo Spek",
    "Zap": "71 99622-9991"
}

###

DELETE http://localhost:8080/user/675402bb-51ae-4914-a9cb-d9f1b7237dfa
Content-Type: application/json

###

PUT http://localhost:8080/user/675402bb-51ae-4914-a9cb-d9f1b7237dfa
Content-Type: application/json

{    
    "name": "Amanda Loiras",
    "zap": "71 98882-2101"
}